### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by withlin** [micro-community/how-to-join#1]
## Who I am

    A gopher.Software Engineer. ❤️ Open Source
## What I want to do
  
   `I am using  go-micro,and then i want to join the community to contribute it.`

**Comment by crazybber** [comment]
approved and you are welcome.

this is an micro open community , you nearly could publish everything  you planed, including  :Product、Unstable、ProtoType、Middle Components、Function Models、Code Snips.

we wish you could join our china  core team finally .

@printfcoder @Allenxuxu
