### ISSUE TITLE
@kuritka

### ISSUE THREAD

**Issue by kuritka** [micro-community/how-to-join#13]
**Who I am**

introduce yourself simply ,to let people have a impression.
Formal C#, .net core developer. Currently GO developer working on decentralized load balancer k8gb.io. 

**What I want to do**
I like your community, observing, hope contributing.

**Comment by crazybber** [comment]
you are wellcome～

**Comment by kuritka** [comment]
Thx @crazybber 🚀  ! will stay in touch!
