### ISSUE TITLE
 [Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by laik** [micro-community/how-to-join#2]
** Who I am **

A gopher.Software Engineer. together c/c++ development.
 
** What I want to do **

framework fix.

**Comment by crazybber** [comment]
approved and you are welcome.

hi @laik  this is an micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.

we wish you could join our china core team finally .

@hb-chen @printfcoder  @Allenxuxu
