### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by weisd** [micro-community/how-to-join#3]
**Who I am**

小公司技术负责人，主导公司golang开发，早期go-micro实践者

**What I want to do**

共同学习，共同进步

**Comment by crazybber** [comment]
approved and you are welcome.

hi @weisd this is an micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.

we wish you could join our china core team finally .

@hb-chen @printfcoder @Allenxuxu
