### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by shabbyboy** [micro-community/how-to-join#4]
**Who I am**
你好，我叫徐晓龙，目前在一家直播公司，做一款直播产品的后台，使用的是golang。之前两份工作：分别是传统医疗行业写后端，用的语言是c#；一家游戏公司，游戏服务器开发，用的是python。
**What I want to do**
今年4月份接触了go-micro了，想参与的go-micro中，做一点事，以前就自己一个瞎折腾，希望找到组织，参与进去

**Comment by crazybber** [comment]
approved and you are already on board, but message reply late, sorry.

hi @shabbyboy  this is an micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.

we wish you could join our china core team finally .

[join in IM Group](https://github.com/micro-in-cn/Notice#%E4%BA%A4%E6%B5%81).

@hb-chen @printfcoder @Allenxuxu
