### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by ping40** [micro-community/how-to-join#5]
**Who I am**

A gopher/javer 喜欢 Open Source

**What I want to do**

想使用micro 开发程序，也希望能够贡献一点代码

**Comment by crazybber** [comment]
invitation sent ,you are welcome on board.

@ping40  this is a micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.
