### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by t5w0rd** [micro-community/how-to-join#6]
**Who I am**
大家好，容我做一下简单自我介绍。本人主要职位是高级后端开发工程师/系统架构师，从业7年，项目经验还算丰富。
关注go-micro项目已有2年左右，曾用go-micro为公司开发过微服务架构的社区系统、分布式推送系统等。
身为程序设计爱好者，在除后端领域外也有一些项目经历，做过一些独立游戏的开发与设计，写过一些黑客工具等等。

**What I want to do**
对go-micro的设计理念非常感兴趣，想同大家一起讨论micro的种种问题，希望能够加入社区。

**Comment by crazybber** [comment]
invitation sent ,you are welcome on board.

@t5w0rd  this is an micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.
