### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by sadwxqezc** [micro-community/how-to-join#7]
Who I am
大家好，我是一个后端开发工程师，工作四年，经历过多个公司，写过JAVA/PHP/GO，目前在成都今日头条。我接触Go有一年了，最近在关注go-micro这个项目，每天会抽时间看邮件/PR/ISSUES。

What I want to do
我对服务框架很感兴趣，因此注意到了go-micro这个项目，也因此发现了这个组织，希望能加入大家，一起为go-micro项目做贡献

**Comment by sadwxqezc** [comment]
@wudi

**Comment by wudi** [comment]
@crazybber

**Comment by crazybber** [comment]
invitation sent ,you are welcome on board.

this is a micro open community , you nearly could publish everything you planed, including :Product、Unstable、Prototype、Middle Components、Function Models、Code Snips.
