### ISSUE TITLE
[Apply to Join] I am a go-micro lover and coder

### ISSUE THREAD

**Issue by yaoyaoio** [micro-community/how-to-join#9]
**Who I am**

大家好 目前本人从事Devops相关工作，对微服务及K8s方向有浓厚的兴趣。

**What I want to do**

在18年底开始使用micro v0.14.1版本开发过游戏相关服务，一直关注micro的发展。

**Comment by sadwxqezc** [comment]
@crazybber

**Comment by crazybber** [comment]
invitation sent @yaoliu 

you are welcome!
